Tracker:AddLocations("locations/Bins Workshop.json")
Tracker:AddLocations("locations/Catch Ammofly.json")
Tracker:AddLocations("locations/Catch Axolotl.json")
Tracker:AddLocations("locations/Catch Bass.json")
Tracker:AddLocations("locations/Catch Bee.json")
Tracker:AddLocations("locations/Catch Beet.json")
Tracker:AddLocations("locations/Catch Bird.json")
Tracker:AddLocations("locations/Catch Blue Jelly.json")
Tracker:AddLocations("locations/Catch Blue Snack.json")
Tracker:AddLocations("locations/Catch Bridge Frog.json")
Tracker:AddLocations("locations/Catch Cicada.json")
Tracker:AddLocations("locations/Catch Crab.json")
Tracker:AddLocations("locations/Catch Cricket.json")
Tracker:AddLocations("locations/Catch Dragonfly.json")
Tracker:AddLocations("locations/Catch Eel.json")
Tracker:AddLocations("locations/Catch Fly.json")
Tracker:AddLocations("locations/Catch Fog Fly.json")
Tracker:AddLocations("locations/Catch Frog.json")
Tracker:AddLocations("locations/Catch Gecko.json")
Tracker:AddLocations("locations/Catch Glowbug.json")
Tracker:AddLocations("locations/Catch Jungle Snack.json")
Tracker:AddLocations("locations/Catch Leafbug.json")
Tracker:AddLocations("locations/Catch Magnet Roach.json")
Tracker:AddLocations("locations/Catch Mantis.json")
Tracker:AddLocations("locations/Catch Minnow.json")
Tracker:AddLocations("locations/Catch Mite.json")
Tracker:AddLocations("locations/Catch Moth.json")
Tracker:AddLocations("locations/Catch Mushfrog.json")
Tracker:AddLocations("locations/Catch Mushroll.json")
Tracker:AddLocations("locations/Catch Mushroom.json")
Tracker:AddLocations("locations/Catch Pecker.json")
Tracker:AddLocations("locations/Catch Purple Snack.json")
Tracker:AddLocations("locations/Catch River Fish.json")
Tracker:AddLocations("locations/Catch Roof Snail.json")
Tracker:AddLocations("locations/Catch Skater.json")
Tracker:AddLocations("locations/Catch Soul Fish.json")
Tracker:AddLocations("locations/Catch Soul Frog.json")
Tracker:AddLocations("locations/Catch Spider.json")
Tracker:AddLocations("locations/Catch Tang.json")
Tracker:AddLocations("locations/Catch Turtle.json")
Tracker:AddLocations("locations/Catch Wormy.json")
Tracker:AddLocations("locations/Cicada Cove.json")
Tracker:AddLocations("locations/City.json")
Tracker:AddLocations("locations/Deep.json")
Tracker:AddLocations("locations/Drywood.json")
Tracker:AddLocations("locations/Estate.json")
Tracker:AddLocations("locations/Fog Garden.json")
Tracker:AddLocations("locations/Forest Floor.json")
Tracker:AddLocations("locations/Green Sea.json")
Tracker:AddLocations("locations/Hive.json")
Tracker:AddLocations("locations/Lost Swamp.json")
Tracker:AddLocations("locations/Marvins Domain.json")
Tracker:AddLocations("locations/Moridonos Domain.json")
Tracker:AddLocations("locations/Old Road.json")
Tracker:AddLocations("locations/Old Wood.json")
Tracker:AddLocations("locations/Outskirts.json")
Tracker:AddLocations("locations/Quarry.json")
Tracker:AddLocations("locations/Reef.json")
Tracker:AddLocations("locations/Ridge.json")
Tracker:AddLocations("locations/Rootden.json")
Tracker:AddLocations("locations/Temple.json")
Tracker:AddLocations("locations/Thickness.json")
Tracker:AddLocations("locations/Treetops.json")
Tracker:AddLocations("locations/Under City.json")
Tracker:AddLocations("locations/Under Under City.json")
Tracker:AddLocations("locations/Very Lost Swamp.json")
Tracker:AddLocations("locations/Well.json")
Tracker:AddLocations("locations/Yellow Forest.json")
Tracker:AddLocations("locations/Overworld.json")
